# -*- coding: utf-8 -*-
"""TopUrbi_rechercheGazetier_Geonames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y3jHeux3XNADEKyR5DJ7IZEdGYWq7wCu
"""

!pip install geocoder

import csv
import pandas as pd
import geocoder

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
alcedo_dossier = "/content/drive/MyDrive/Colab Notebooks"


# Pour lire le fichier csv

Alcedo_df = pd.read_csv(alcedo_dossier + '/alcedo-1-utf8.xml.csv', delimiter='|')

# Attraper les entrees sans settlement

entrees_sans_settlement = Alcedo_df[Alcedo_df['settlement'].isnull()]

print("entrees_sans_settlement: "+str(len(entrees_sans_settlement)))

# Filtrer avec les type_lieu

lieux_sans_settlement_types = entrees_sans_settlement.loc[entrees_sans_settlement['type_lieu' ].isin(["Pueblo","Nación", "Provincia", "Isla", "Ciudad", "Alcaldía"])] 
#display(entrees_sans_settlement['nom_lieu'])
#.isin([3, 6])

print("lieux_sans_settlement_types: "+str(len(lieux_sans_settlement_types)))

#dataframe.loc[dataframe['Percentage'] > 80]

count_stop = 0
for ind in lieux_sans_settlement_types.index:
  #print(lieux_sans_settlement_types['nom_lieu'][ind], lieux_sans_settlement_types['type_lieu'][ind])
  nom_lieu = lieux_sans_settlement_types['nom_lieu'][ind]
  #print(nom_lieu)
  if (count_stop < 20):
# appel API geonames : https://geocoder.readthedocs.io/providers/GeoNames.html 
    print(nom_lieu)
    g = geocoder.geonames(nom_lieu, key='cvbrandoe') #créer un compte ici : https://www.geonames.org/login 
    print("result_geocodage")
    print(g)
    print("")
  count_stop = count_stop + 1